name: Test Build Python Exe

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: main
        artifact: Program
        use-dependencies: false
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: python_exe
        path: dist
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: main
          artifact: Program
          use-dependencies: false
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: python_exe
          path: dist
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: "1.0.0"
          prerelease: false
          title: "Windows"
          files: |
            ./dist/python_exe.exe
